site_name: Nicolás Lozano Amaya
site_url: https://mekhapp.github.io/nicolozama.github.io/
site_author: Nicolás Lozano Amaya
site_description: >-
  Soy ingeniero mecánico con gran interés en el área de tecnología en detalle
  la automatización de sistemas de fábricas de datos desde la ingesta desde
  múltiples fuentes con trasformación optimizada y disposición en repositorios.
  Además, generar toma de decisiones a partir de los datos es otro punto en mis
  actividades, creando backends para la interacción que el negocio necesita dar
  de forma oportuna y relevante al usuario en su dominio. También puedes
  encontrar los temas que me están interesando. Trataré temas de desde la
  tecnología hasta temas históricos y filosóficos.
theme:
  name: terminal

nav:
  - sobre mi: 'index.md'
  - código: 'código/index.md'
  - filosofía: 'filosofía/index.md'
  - historia: 'historia/index.md'
