site_name: Nicolás Lozano Amaya
site_url: https://mekhapp.github.io/nicolozama.github.io/
site_author: Nicolás Lozano Amaya
site_description: >-
  Soy ingeniero mecánico con gran interés en el área de tecnología en detalle
  la automatización de sistemas de fábricas de datos desde la ingesta de
  múltiples fuentes, información optimizada y disposición en repositorios.
  Además, el reflejo de los datos es otro punto en mis actividades, creando
  backends para la interacción que el negocio necesita dar de forma oportuna y
  relevante al usuario en su dominio. También puedes encontrar los
  temas que me están interesando. Trataré temas de desde la tecnología hasta
  temas sociales, económicos y filosóficos.
theme:
  name: terminal


nav:
  - sobre mi: 'index.md'
  - código: 'codigo/index.md'
  - filosofía: 'filosofia/index.md'
  - economía: 'filosofia/index.md'
